name: myMoon
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.0-146.2.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  qr_code_scanner: ^1.0.1
  audioplayers: ^4.1.0
  cryptography: ^2.5.0
  lottie: ^2.3.2
  # permission_handler: ^11.0.1
  # video_player: ^2.8.1
  o3d: ^3.1.0
  flutter_launcher_icons: ^0.13.1
  model_viewer_plus: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/ic_launcher.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/lottie/
    - assets/voice5.mp3
    - assets/image11.jpg
    # - assets/logo.json
    - assets/images/
    # - assets/images/thired.png
    - assets/font/
    - assets/icon/icon.png
    - assets/Logo.png
    - assets/ic_launcher.png
    - assets/Logo0.png
    - assets/models/

  fonts:
    - family: first
      fonts:
        - asset: assets/font/Arabic.ttf
    - family: second
      fonts:
        - asset: assets/font/Iranian Sans.ttf

    - family: thired
      fonts:
        - asset: assets/font/Shabnam.ttf

